---
# Handler to common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart redis
  service: name=redis-server state=restarted

- name: restart sentinel
  service: name=redis-sentinel state=restarted

- name: restart haproxy
  service: name=haproxy state=restarted
